#!/usr/bin/env sh
stash_count_before=$(git stash list | wc -l)
git stash -q --keep-index --include-untracked
stash_count_after=$(git stash list | wc -l)

if [ $? -ne 0 ]; then
    echo "Stashing unstaged changes failed!"
    exit 1
fi

git diff --name-only --cached --diff-filter=d | xargs prettier --check
if [ $? -ne 0 ]; then
    echo "Files not formatted!"
    exit 1
fi

npm test -- --onlyChanged --forceExit
if [ $? -ne 0 ]; then
    echo "Tests failed!"
    exit 1
fi

if (( stash_count_after > stash_count_before )); then
    git stash pop -q
fi

exit 0
